
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jokhi
 */
public class MainFramPinCode extends javax.swing.JFrame {

    /**
     * Creates new form MainFramPinCode
     */
    
    
    String  pincode;
    
    public MainFramPinCode() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_1 = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        btn_5 = new javax.swing.JButton();
        btn_6 = new javax.swing.JButton();
        btn_4 = new javax.swing.JButton();
        btn_3 = new javax.swing.JButton();
        btn_7 = new javax.swing.JButton();
        btn_0 = new javax.swing.JButton();
        btn_8 = new javax.swing.JButton();
        btn_9 = new javax.swing.JButton();
        btn_enter = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        pin_txt = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Serif", 3, 54)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(5, 5, 186));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("WELCOME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 310, 80));

        jLabel1.setFont(new java.awt.Font("SimSun-ExtB", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(5, 5, 186));
        jLabel1.setText("Please enter your 4 digit pin");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 500, 60));

        btn_1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_1.setForeground(new java.awt.Color(5, 5, 186));
        btn_1.setText("1");
        btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 60, 60));

        btn_2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_2.setForeground(new java.awt.Color(5, 5, 186));
        btn_2.setText("2");
        btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 60, 60));

        btn_5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_5.setForeground(new java.awt.Color(5, 5, 186));
        btn_5.setText("5");
        btn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 60, 60));

        btn_6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_6.setForeground(new java.awt.Color(5, 5, 186));
        btn_6.setText("6");
        btn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 60, 60));

        btn_4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_4.setForeground(new java.awt.Color(5, 5, 186));
        btn_4.setText("4");
        btn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, 60, 60));

        btn_3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_3.setForeground(new java.awt.Color(5, 5, 186));
        btn_3.setText("3");
        btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 60, 60));

        btn_7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_7.setForeground(new java.awt.Color(5, 5, 186));
        btn_7.setText("7");
        btn_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_7ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 460, 60, 60));

        btn_0.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_0.setForeground(new java.awt.Color(5, 5, 186));
        btn_0.setText("0");
        btn_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_0ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 550, 60, 60));

        btn_8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_8.setForeground(new java.awt.Color(5, 5, 186));
        btn_8.setText("8");
        btn_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_8ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 460, 60, 60));

        btn_9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_9.setForeground(new java.awt.Color(5, 5, 186));
        btn_9.setText("9");
        btn_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_9ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 550, 60, 60));

        btn_enter.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_enter.setForeground(new java.awt.Color(5, 5, 186));
        btn_enter.setText("Enter");
        btn_enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enterActionPerformed(evt);
            }
        });
        getContentPane().add(btn_enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 570, 110, 50));

        btn_clear.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_clear.setForeground(new java.awt.Color(5, 5, 186));
        btn_clear.setText("Clear");
        getContentPane().add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 570, 110, 50));

        pin_txt.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        pin_txt.setForeground(new java.awt.Color(5, 5, 186));
        pin_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pin_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pin_txtActionPerformed(evt);
            }
        });
        getContentPane().add(pin_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 410, 60));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed
     
        pincode=pin_txt.getText()+btn_1.getText();
        
        if(pincode.length()<5){
        
        pin_txt.setText(pincode);
        }
        
     if(pincode.length()==4){
     
      Timer delay= new Timer(500, new ActionListener() {
        
        @Override
        public void actionPerformed(ActionEvent e) {
            ATM db = new ATM();
            setVisible(false);
            db.setVisible(true);
        }
    });
    delay.setRepeats(false);
    delay.start();
        
    }      
    }//GEN-LAST:event_btn_1ActionPerformed

    private void btn_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_8ActionPerformed
    
   pincode=pin_txt.getText()+btn_8.getText();
        if(pincode.length()<5){        
        pin_txt.setText(pincode);
        }
       
     if(pincode.length()==4){
     
      Timer delay= new Timer(500, new ActionListener() {
        
        @Override
        public void actionPerformed(ActionEvent e) {
            ATM db = new ATM();
            setVisible(false);
            db.setVisible(true);
        }
    });

     
    delay.setRepeats(false);
    delay.start();
        
    }    
    }//GEN-LAST:event_btn_8ActionPerformed

    private void btn_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_9ActionPerformed
     
     pincode=pin_txt.getText()+btn_9.getText();
        if(pincode.length()<5){
        pin_txt.setText(pincode);
        }
       
     if(pincode.length()==4){
     
      Timer delay= new Timer(500, new ActionListener() {
        
        @Override
        public void actionPerformed(ActionEvent e) {
            ATM db = new ATM();
            setVisible(false);
            db.setVisible(true);
        }
    });

     
    delay.setRepeats(false);
    delay.start();
        
    } 
    }//GEN-LAST:event_btn_9ActionPerformed

    private void btn_enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enterActionPerformed
        
       ATM db=new ATM();
        this.setVisible(false);
        db.setVisible(true);
        
    }//GEN-LAST:event_btn_enterActionPerformed

    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
      
     pincode=pin_txt.getText()+btn_2.getText();
       if(pincode.length()<5){        
        pin_txt.setText(pincode);
        }
       
     if(pincode.length()==4){
     
      Timer delay= new Timer(500, new ActionListener() {
        
        @Override
        public void actionPerformed(ActionEvent e) {
            ATM db = new ATM();
            setVisible(false);
            db.setVisible(true);
        }
    });

     
    delay.setRepeats(false);
    delay.start();
        
    } 
    }//GEN-LAST:event_btn_2ActionPerformed

    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
     
     pincode=pin_txt.getText()+btn_3.getText();
        if(pincode.length()<5){        
        pin_txt.setText(pincode);
        }
       
     if(pincode.length()==4){
     
      Timer delay= new Timer(500, new ActionListener() {
        
        @Override
        public void actionPerformed(ActionEvent e) {
            ATM db = new ATM();
            setVisible(false);
            db.setVisible(true);
        }
    });

     
    delay.setRepeats(false);
    delay.start();
        
    } 
    }//GEN-LAST:event_btn_3ActionPerformed

    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed
    
     pincode=pin_txt.getText()+btn_4.getText();
        if(pincode.length()<5){        
        pin_txt.setText(pincode);
        }
       
     if(pincode.length()==4){
     
      Timer delay= new Timer(500, new ActionListener() {
        
        @Override
        public void actionPerformed(ActionEvent e) {
            ATM db = new ATM();
            setVisible(false);
            db.setVisible(true);
        }
    });

     
    delay.setRepeats(false);
    delay.start();
        
    } 
    }//GEN-LAST:event_btn_4ActionPerformed

    private void btn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_5ActionPerformed
    
     pincode=pin_txt.getText()+btn_5.getText();
        if(pincode.length()<5){        
        pin_txt.setText(pincode);
        }
       
     if(pincode.length()==4){
     
      Timer delay= new Timer(500, new ActionListener() {
        
        @Override
        public void actionPerformed(ActionEvent e) {
            ATM db = new ATM();
            setVisible(false);
            db.setVisible(true);
        }
    });

     
    delay.setRepeats(false);
    delay.start();
        
    } 
    }//GEN-LAST:event_btn_5ActionPerformed

    private void btn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_6ActionPerformed
  
     pincode=pin_txt.getText()+btn_6.getText();
        if(pincode.length()<5){        
        pin_txt.setText(pincode);
        }
       
     if(pincode.length()==4){
     
      Timer delay= new Timer(500, new ActionListener() {
        
        @Override
        public void actionPerformed(ActionEvent e) {
            ATM db = new ATM();
            setVisible(false);
            db.setVisible(true);
        }
    });

     
    delay.setRepeats(false);
    delay.start();
        
    } 
    }//GEN-LAST:event_btn_6ActionPerformed

    private void btn_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_7ActionPerformed
     pincode=pin_txt.getText()+btn_7.getText();
        if(pincode.length()<5){        
        pin_txt.setText(pincode);
        }
       
     if(pincode.length()==4){
     
      Timer delay= new Timer(500, new ActionListener() {
        
        @Override
        public void actionPerformed(ActionEvent e) {
            ATM db = new ATM();
            setVisible(false);
            db.setVisible(true);
        }
    });

     
    delay.setRepeats(false);
    delay.start();
        
    } 
    }//GEN-LAST:event_btn_7ActionPerformed

                
    private void btn_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_0ActionPerformed
    
     pincode=pin_txt.getText()+btn_0.getText();
        if(pincode.length()<5){        
        pin_txt.setText(pincode);
        }
       
     if(pincode.length()==4){
     
      Timer delay= new Timer(500, new ActionListener() {
        
        @Override
        public void actionPerformed(ActionEvent e) {
            ATM db = new ATM();
            setVisible(false);
            db.setVisible(true);
        }
    });

     
    delay.setRepeats(false);
    delay.start();
        
    } 
    }//GEN-LAST:event_btn_0ActionPerformed

    private void pin_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pin_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pin_txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFramPinCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFramPinCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFramPinCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFramPinCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFramPinCode().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_0;
    private javax.swing.JButton btn_1;
    private javax.swing.JButton btn_2;
    private javax.swing.JButton btn_3;
    private javax.swing.JButton btn_4;
    private javax.swing.JButton btn_5;
    private javax.swing.JButton btn_6;
    private javax.swing.JButton btn_7;
    private javax.swing.JButton btn_8;
    private javax.swing.JButton btn_9;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_enter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField pin_txt;
    // End of variables declaration//GEN-END:variables
}
